// GENERATED by scripts/gen-db-types.ts — do not edit by hand. Run `npm run db:types`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" };
  public: {
    Tables: {
      access_tokens: {
        Row: {
          id: string;
          token_hash: string;
          scope: string;
          lead_id: string;
          expires_at: string;
          revoked_at: string | null;
          last_used_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          token_hash: string;
          scope?: string;
          lead_id: string;
          expires_at: string;
          revoked_at?: string | null;
          last_used_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          token_hash?: string;
          scope?: string;
          lead_id?: string;
          expires_at?: string;
          revoked_at?: string | null;
          last_used_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "access_tokens_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      admin_notes: {
        Row: {
          id: string;
          lead_id: string;
          author_id: string | null;
          body: string;
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          author_id?: string | null;
          body: string;
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          author_id?: string | null;
          body?: string;
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "admin_notes_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "admin_notes_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_generations: {
        Row: {
          id: string;
          agent: string;
          lead_id: string | null;
          booking_id: string | null;
          media_id: string | null;
          showcase_id: string | null;
          input: Json;
          output: Json | null;
          provider: string;
          model: string | null;
          status: Database["public"]["Enums"]["ai_generation_status"];
          error: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          agent: string;
          lead_id?: string | null;
          booking_id?: string | null;
          media_id?: string | null;
          showcase_id?: string | null;
          input?: Json;
          output?: Json | null;
          provider: string;
          model?: string | null;
          status?: Database["public"]["Enums"]["ai_generation_status"];
          error?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          agent?: string;
          lead_id?: string | null;
          booking_id?: string | null;
          media_id?: string | null;
          showcase_id?: string | null;
          input?: Json;
          output?: Json | null;
          provider?: string;
          model?: string | null;
          status?: Database["public"]["Enums"]["ai_generation_status"];
          error?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_generations_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_generations_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_generations_media_id_fkey";
            columns: ["media_id"];
            isOneToOne: false;
            referencedRelation: "media";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_generations_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_generations_showcase_id_fkey";
            columns: ["showcase_id"];
            isOneToOne: false;
            referencedRelation: "showcases";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          actor_type: string;
          action: string;
          entity_type: string;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          actor_type?: string;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          actor_type?: string;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      automation_rules: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string;
          trigger_event: string;
          delay_minutes: number;
          channel: string;
          template_key: string | null;
          agent: string | null;
          is_enabled: boolean;
          auto_send: boolean;
          conditions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string;
          trigger_event: string;
          delay_minutes?: number;
          channel?: string;
          template_key?: string | null;
          agent?: string | null;
          is_enabled?: boolean;
          auto_send?: boolean;
          conditions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string;
          trigger_event?: string;
          delay_minutes?: number;
          channel?: string;
          template_key?: string | null;
          agent?: string | null;
          is_enabled?: boolean;
          auto_send?: boolean;
          conditions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      automation_runs: {
        Row: {
          id: string;
          rule_id: string;
          lead_id: string | null;
          booking_id: string | null;
          domain_event_id: string | null;
          status: Database["public"]["Enums"]["automation_run_status"];
          scheduled_for: string;
          executed_at: string | null;
          attempts: number;
          dedupe_key: string;
          result: Json | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          rule_id: string;
          lead_id?: string | null;
          booking_id?: string | null;
          domain_event_id?: string | null;
          status?: Database["public"]["Enums"]["automation_run_status"];
          scheduled_for: string;
          executed_at?: string | null;
          attempts?: number;
          dedupe_key: string;
          result?: Json | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          rule_id?: string;
          lead_id?: string | null;
          booking_id?: string | null;
          domain_event_id?: string | null;
          status?: Database["public"]["Enums"]["automation_run_status"];
          scheduled_for?: string;
          executed_at?: string | null;
          attempts?: number;
          dedupe_key?: string;
          result?: Json | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "automation_runs_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "automation_runs_domain_event_id_fkey";
            columns: ["domain_event_id"];
            isOneToOne: false;
            referencedRelation: "domain_events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "automation_runs_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "automation_runs_rule_id_fkey";
            columns: ["rule_id"];
            isOneToOne: false;
            referencedRelation: "automation_rules";
            referencedColumns: ["id"];
          },
        ];
      };
      availability_blocks: {
        Row: {
          id: string;
          starts_at: string;
          ends_at: string;
          reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          starts_at: string;
          ends_at: string;
          reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          starts_at?: string;
          ends_at?: string;
          reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "availability_blocks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      bookings: {
        Row: {
          id: string;
          number: string;
          lead_id: string;
          quote_id: string;
          contract_id: string | null;
          status: Database["public"]["Enums"]["booking_status"];
          total_cents: number;
          deposit_cents: number;
          amount_paid_cents: number;
          confirmed_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancellation_reason: string | null;
          external_calendar_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: string;
          lead_id: string;
          quote_id: string;
          contract_id?: string | null;
          status?: Database["public"]["Enums"]["booking_status"];
          total_cents: number;
          deposit_cents: number;
          amount_paid_cents?: number;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          external_calendar_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string;
          lead_id?: string;
          quote_id?: string;
          contract_id?: string | null;
          status?: Database["public"]["Enums"]["booking_status"];
          total_cents?: number;
          deposit_cents?: number;
          amount_paid_cents?: number;
          confirmed_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
          external_calendar_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "bookings_contract_id_fkey";
            columns: ["contract_id"];
            isOneToOne: false;
            referencedRelation: "contracts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bookings_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: true;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "bookings_quote_id_fkey";
            columns: ["quote_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id"];
          },
        ];
      };
      contract_signatures: {
        Row: {
          id: string;
          contract_id: string;
          signer_name: string;
          signer_email: string | null;
          agreed: boolean;
          signed_at: string;
          ip_address: string | null;
          user_agent: string | null;
          contract_version: number;
          content_hash: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          contract_id: string;
          signer_name: string;
          signer_email?: string | null;
          agreed: boolean;
          signed_at?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          contract_version: number;
          content_hash: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          contract_id?: string;
          signer_name?: string;
          signer_email?: string | null;
          agreed?: boolean;
          signed_at?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          contract_version?: number;
          content_hash?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contract_signatures_contract_id_fkey";
            columns: ["contract_id"];
            isOneToOne: true;
            referencedRelation: "contracts";
            referencedColumns: ["id"];
          },
        ];
      };
      contract_templates: {
        Row: {
          id: string;
          name: string;
          version: number;
          body: string;
          is_default: boolean;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          version?: number;
          body: string;
          is_default?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          version?: number;
          body?: string;
          is_default?: boolean;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contract_templates_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      contracts: {
        Row: {
          id: string;
          number: string;
          lead_id: string;
          quote_id: string;
          template_id: string | null;
          template_version: number;
          status: Database["public"]["Enums"]["contract_status"];
          body: string;
          variables: Json;
          content_hash: string;
          sent_at: string | null;
          viewed_at: string | null;
          signed_at: string | null;
          voided_at: string | null;
          void_reason: string | null;
          pdf_path: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: string;
          lead_id: string;
          quote_id: string;
          template_id?: string | null;
          template_version: number;
          status?: Database["public"]["Enums"]["contract_status"];
          body: string;
          variables?: Json;
          content_hash: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          signed_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          pdf_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string;
          lead_id?: string;
          quote_id?: string;
          template_id?: string | null;
          template_version?: number;
          status?: Database["public"]["Enums"]["contract_status"];
          body?: string;
          variables?: Json;
          content_hash?: string;
          sent_at?: string | null;
          viewed_at?: string | null;
          signed_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          pdf_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contracts_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contracts_quote_id_fkey";
            columns: ["quote_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contracts_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "contract_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      customers: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      domain_events: {
        Row: {
          id: string;
          type: string;
          lead_id: string | null;
          booking_id: string | null;
          payload: Json;
          actor: string;
          occurred_at: string;
          processed_at: string | null;
          attempts: number;
          last_error: string | null;
        };
        Insert: {
          id?: string;
          type: string;
          lead_id?: string | null;
          booking_id?: string | null;
          payload?: Json;
          actor?: string;
          occurred_at?: string;
          processed_at?: string | null;
          attempts?: number;
          last_error?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          lead_id?: string | null;
          booking_id?: string | null;
          payload?: Json;
          actor?: string;
          occurred_at?: string;
          processed_at?: string | null;
          attempts?: number;
          last_error?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "domain_events_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "domain_events_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      event_types: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          event_type_id: string | null;
          title: string;
          event_date: string;
          start_time: string;
          end_time: string | null;
          duration_minutes: number;
          starts_at: string;
          ends_at: string;
          travel_buffer_minutes: number;
          venue_id: string | null;
          guest_count: number | null;
          planner_name: string | null;
          planner_email: string | null;
          planner_phone: string | null;
          special_instructions: string | null;
          entrance_instructions: string | null;
          special_songs: string | null;
          itinerary_path: string | null;
          venue_instructions_path: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_type_id?: string | null;
          title: string;
          event_date: string;
          start_time: string;
          end_time?: string | null;
          duration_minutes: number;
          starts_at: string;
          ends_at: string;
          travel_buffer_minutes?: number;
          venue_id?: string | null;
          guest_count?: number | null;
          planner_name?: string | null;
          planner_email?: string | null;
          planner_phone?: string | null;
          special_instructions?: string | null;
          entrance_instructions?: string | null;
          special_songs?: string | null;
          itinerary_path?: string | null;
          venue_instructions_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_type_id?: string | null;
          title?: string;
          event_date?: string;
          start_time?: string;
          end_time?: string | null;
          duration_minutes?: number;
          starts_at?: string;
          ends_at?: string;
          travel_buffer_minutes?: number;
          venue_id?: string | null;
          guest_count?: number | null;
          planner_name?: string | null;
          planner_email?: string | null;
          planner_phone?: string | null;
          special_instructions?: string | null;
          entrance_instructions?: string | null;
          special_songs?: string | null;
          itinerary_path?: string | null;
          venue_instructions_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_event_type_id_fkey";
            columns: ["event_type_id"];
            isOneToOne: false;
            referencedRelation: "event_types";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_venue_id_fkey";
            columns: ["venue_id"];
            isOneToOne: false;
            referencedRelation: "venues";
            referencedColumns: ["id"];
          },
        ];
      };
      leads: {
        Row: {
          id: string;
          reference: string;
          customer_id: string;
          event_id: string;
          service_id: string | null;
          package_id: string | null;
          requested_service_label: string | null;
          status: Database["public"]["Enums"]["lead_status"];
          status_changed_at: string;
          availability_status: Database["public"]["Enums"]["availability_status"];
          availability_checked_at: string | null;
          availability_details: Json;
          availability_override: boolean;
          availability_override_by: string | null;
          urgency: string | null;
          ai_summary: Json | null;
          message: string | null;
          source: string;
          utm: Json;
          estimated_value_cents: number | null;
          lost_reason: string | null;
          assigned_to: string | null;
          last_contacted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference: string;
          customer_id: string;
          event_id: string;
          service_id?: string | null;
          package_id?: string | null;
          requested_service_label?: string | null;
          status?: Database["public"]["Enums"]["lead_status"];
          status_changed_at?: string;
          availability_status?: Database["public"]["Enums"]["availability_status"];
          availability_checked_at?: string | null;
          availability_details?: Json;
          availability_override?: boolean;
          availability_override_by?: string | null;
          urgency?: string | null;
          ai_summary?: Json | null;
          message?: string | null;
          source?: string;
          utm?: Json;
          estimated_value_cents?: number | null;
          lost_reason?: string | null;
          assigned_to?: string | null;
          last_contacted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reference?: string;
          customer_id?: string;
          event_id?: string;
          service_id?: string | null;
          package_id?: string | null;
          requested_service_label?: string | null;
          status?: Database["public"]["Enums"]["lead_status"];
          status_changed_at?: string;
          availability_status?: Database["public"]["Enums"]["availability_status"];
          availability_checked_at?: string | null;
          availability_details?: Json;
          availability_override?: boolean;
          availability_override_by?: string | null;
          urgency?: string | null;
          ai_summary?: Json | null;
          message?: string | null;
          source?: string;
          utm?: Json;
          estimated_value_cents?: number | null;
          lost_reason?: string | null;
          assigned_to?: string | null;
          last_contacted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "leads_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_availability_override_by_fkey";
            columns: ["availability_override_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: true;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_package_id_fkey";
            columns: ["package_id"];
            isOneToOne: false;
            referencedRelation: "packages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      media: {
        Row: {
          id: string;
          showcase_id: string | null;
          event_id: string | null;
          event_type_id: string | null;
          service_id: string | null;
          kind: Database["public"]["Enums"]["media_kind"];
          storage_path: string | null;
          url: string;
          poster_url: string | null;
          width: number | null;
          height: number | null;
          duration_seconds: number | null;
          size_bytes: number | null;
          blur_data_url: string | null;
          alt_text: string | null;
          caption: string | null;
          venue_name: string | null;
          taken_on: string | null;
          is_published: boolean;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          showcase_id?: string | null;
          event_id?: string | null;
          event_type_id?: string | null;
          service_id?: string | null;
          kind: Database["public"]["Enums"]["media_kind"];
          storage_path?: string | null;
          url: string;
          poster_url?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          size_bytes?: number | null;
          blur_data_url?: string | null;
          alt_text?: string | null;
          caption?: string | null;
          venue_name?: string | null;
          taken_on?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          showcase_id?: string | null;
          event_id?: string | null;
          event_type_id?: string | null;
          service_id?: string | null;
          kind?: Database["public"]["Enums"]["media_kind"];
          storage_path?: string | null;
          url?: string;
          poster_url?: string | null;
          width?: number | null;
          height?: number | null;
          duration_seconds?: number | null;
          size_bytes?: number | null;
          blur_data_url?: string | null;
          alt_text?: string | null;
          caption?: string | null;
          venue_name?: string | null;
          taken_on?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "media_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_event_type_id_fkey";
            columns: ["event_type_id"];
            isOneToOne: false;
            referencedRelation: "event_types";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_showcase_id_fkey";
            columns: ["showcase_id"];
            isOneToOne: false;
            referencedRelation: "showcases";
            referencedColumns: ["id"];
          },
        ];
      };
      message_templates: {
        Row: {
          id: string;
          key: string;
          channel: string;
          name: string;
          subject: string | null;
          body: string;
          auto_send_allowed: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          channel: string;
          name: string;
          subject?: string | null;
          body: string;
          auto_send_allowed?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          channel?: string;
          name?: string;
          subject?: string | null;
          body?: string;
          auto_send_allowed?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          lead_id: string | null;
          booking_id: string | null;
          customer_id: string | null;
          type: Database["public"]["Enums"]["message_type"];
          direction: Database["public"]["Enums"]["message_direction"];
          status: Database["public"]["Enums"]["delivery_status"];
          sender: string | null;
          recipient: string | null;
          subject: string | null;
          body: string;
          template_key: string | null;
          provider: string | null;
          provider_message_id: string | null;
          error: string | null;
          ai_generation_id: string | null;
          automation_run_id: string | null;
          created_by: string | null;
          sent_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id?: string | null;
          booking_id?: string | null;
          customer_id?: string | null;
          type: Database["public"]["Enums"]["message_type"];
          direction: Database["public"]["Enums"]["message_direction"];
          status?: Database["public"]["Enums"]["delivery_status"];
          sender?: string | null;
          recipient?: string | null;
          subject?: string | null;
          body: string;
          template_key?: string | null;
          provider?: string | null;
          provider_message_id?: string | null;
          error?: string | null;
          ai_generation_id?: string | null;
          automation_run_id?: string | null;
          created_by?: string | null;
          sent_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string | null;
          booking_id?: string | null;
          customer_id?: string | null;
          type?: Database["public"]["Enums"]["message_type"];
          direction?: Database["public"]["Enums"]["message_direction"];
          status?: Database["public"]["Enums"]["delivery_status"];
          sender?: string | null;
          recipient?: string | null;
          subject?: string | null;
          body?: string;
          template_key?: string | null;
          provider?: string | null;
          provider_message_id?: string | null;
          error?: string | null;
          ai_generation_id?: string | null;
          automation_run_id?: string | null;
          created_by?: string | null;
          sent_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_ai_generation_id_fkey";
            columns: ["ai_generation_id"];
            isOneToOne: false;
            referencedRelation: "ai_generations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_automation_run_fk";
            columns: ["automation_run_id"];
            isOneToOne: false;
            referencedRelation: "automation_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
        ];
      };
      number_sequences: {
        Row: {
          scope: string;
          year: number;
          last_value: number;
        };
        Insert: {
          scope: string;
          year: number;
          last_value?: number;
        };
        Update: {
          scope?: string;
          year?: number;
          last_value?: number;
        };
        Relationships: [];
      };
      package_services: {
        Row: {
          package_id: string;
          service_id: string;
          quantity: number;
        };
        Insert: {
          package_id: string;
          service_id: string;
          quantity?: number;
        };
        Update: {
          package_id?: string;
          service_id?: string;
          quantity?: number;
        };
        Relationships: [
          {
            foreignKeyName: "package_services_package_id_fkey";
            columns: ["package_id"];
            isOneToOne: false;
            referencedRelation: "packages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "package_services_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      packages: {
        Row: {
          id: string;
          slug: string;
          name: string;
          tagline: string;
          description: string;
          highlights: string[];
          image_url: string | null;
          price_from_cents: number | null;
          is_active: boolean;
          is_featured: boolean;
          is_coming_soon: boolean;
          sort_order: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          tagline?: string;
          description?: string;
          highlights?: string[];
          image_url?: string | null;
          price_from_cents?: number | null;
          is_active?: boolean;
          is_featured?: boolean;
          is_coming_soon?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          tagline?: string;
          description?: string;
          highlights?: string[];
          image_url?: string | null;
          price_from_cents?: number | null;
          is_active?: boolean;
          is_featured?: boolean;
          is_coming_soon?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          kind: Database["public"]["Enums"]["payment_kind"];
          status: Database["public"]["Enums"]["payment_status"];
          amount_cents: number;
          refunded_cents: number;
          currency: string;
          stripe_checkout_session_id: string | null;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_customer_id: string | null;
          receipt_number: string | null;
          receipt_url: string | null;
          failure_reason: string | null;
          paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          kind: Database["public"]["Enums"]["payment_kind"];
          status?: Database["public"]["Enums"]["payment_status"];
          amount_cents: number;
          refunded_cents?: number;
          currency?: string;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          receipt_number?: string | null;
          receipt_url?: string | null;
          failure_reason?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          kind?: Database["public"]["Enums"]["payment_kind"];
          status?: Database["public"]["Enums"]["payment_status"];
          amount_cents?: number;
          refunded_cents?: number;
          currency?: string;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_customer_id?: string | null;
          receipt_number?: string | null;
          receipt_url?: string | null;
          failure_reason?: string | null;
          paid_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_booking_id_fkey";
            columns: ["booking_id"];
            isOneToOne: false;
            referencedRelation: "bookings";
            referencedColumns: ["id"];
          },
        ];
      };
      quote_items: {
        Row: {
          id: string;
          quote_id: string;
          service_id: string | null;
          description: string;
          quantity: number;
          unit_price_cents: number;
          total_cents: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          service_id?: string | null;
          description: string;
          quantity?: number;
          unit_price_cents: number;
          total_cents: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          service_id?: string | null;
          description?: string;
          quantity?: number;
          unit_price_cents?: number;
          total_cents?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quote_items_quote_id_fkey";
            columns: ["quote_id"];
            isOneToOne: false;
            referencedRelation: "quotes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quote_items_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      quotes: {
        Row: {
          id: string;
          number: string;
          lead_id: string;
          package_id: string | null;
          status: Database["public"]["Enums"]["quote_status"];
          performance_minutes: number;
          performers: number;
          base_fee_cents: number;
          travel_fee_cents: number;
          additional_fee_cents: number;
          discount_cents: number;
          tax_rate_bps: number;
          tax_cents: number;
          total_cents: number;
          deposit_cents: number;
          balance_cents: number;
          notes: string | null;
          expires_on: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          accepted_at: string | null;
          declined_at: string | null;
          decline_reason: string | null;
          customer_question: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: string;
          lead_id: string;
          package_id?: string | null;
          status?: Database["public"]["Enums"]["quote_status"];
          performance_minutes: number;
          performers?: number;
          base_fee_cents?: number;
          travel_fee_cents?: number;
          additional_fee_cents?: number;
          discount_cents?: number;
          tax_rate_bps?: number;
          tax_cents?: number;
          total_cents: number;
          deposit_cents: number;
          balance_cents: number;
          notes?: string | null;
          expires_on?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          declined_at?: string | null;
          decline_reason?: string | null;
          customer_question?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string;
          lead_id?: string;
          package_id?: string | null;
          status?: Database["public"]["Enums"]["quote_status"];
          performance_minutes?: number;
          performers?: number;
          base_fee_cents?: number;
          travel_fee_cents?: number;
          additional_fee_cents?: number;
          discount_cents?: number;
          tax_rate_bps?: number;
          tax_cents?: number;
          total_cents?: number;
          deposit_cents?: number;
          balance_cents?: number;
          notes?: string | null;
          expires_on?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          accepted_at?: string | null;
          declined_at?: string | null;
          decline_reason?: string | null;
          customer_question?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quotes_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotes_lead_id_fkey";
            columns: ["lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quotes_package_id_fkey";
            columns: ["package_id"];
            isOneToOne: false;
            referencedRelation: "packages";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limits: {
        Row: {
          key: string;
          count: number;
          window_start: string;
        };
        Insert: {
          key: string;
          count?: number;
          window_start?: string;
        };
        Update: {
          key?: string;
          count?: number;
          window_start?: string;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          slug: string;
          name: string;
          category: string;
          short_description: string;
          description: string;
          typical_use: string;
          image_url: string | null;
          performers: number;
          base_price_cents: number | null;
          included_minutes: number | null;
          extra_hour_cents: number | null;
          min_duration_minutes: number;
          is_active: boolean;
          is_featured: boolean;
          is_bookable: boolean;
          is_coming_soon: boolean;
          sort_order: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          category?: string;
          short_description?: string;
          description?: string;
          typical_use?: string;
          image_url?: string | null;
          performers?: number;
          base_price_cents?: number | null;
          included_minutes?: number | null;
          extra_hour_cents?: number | null;
          min_duration_minutes?: number;
          is_active?: boolean;
          is_featured?: boolean;
          is_bookable?: boolean;
          is_coming_soon?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          category?: string;
          short_description?: string;
          description?: string;
          typical_use?: string;
          image_url?: string | null;
          performers?: number;
          base_price_cents?: number | null;
          included_minutes?: number | null;
          extra_hour_cents?: number | null;
          min_duration_minutes?: number;
          is_active?: boolean;
          is_featured?: boolean;
          is_bookable?: boolean;
          is_coming_soon?: boolean;
          sort_order?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          key: string;
          value: Json;
          is_public: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          is_public?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      showcases: {
        Row: {
          id: string;
          slug: string;
          title: string;
          event_type_id: string | null;
          service_id: string | null;
          event_id: string | null;
          venue_name: string | null;
          city: string | null;
          event_date: string | null;
          description: string | null;
          is_published: boolean;
          is_featured: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
          cover_media_id: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          title: string;
          event_type_id?: string | null;
          service_id?: string | null;
          event_id?: string | null;
          venue_name?: string | null;
          city?: string | null;
          event_date?: string | null;
          description?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          cover_media_id?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          title?: string;
          event_type_id?: string | null;
          service_id?: string | null;
          event_id?: string | null;
          venue_name?: string | null;
          city?: string | null;
          event_date?: string | null;
          description?: string | null;
          is_published?: boolean;
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          cover_media_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "showcases_cover_media_id_fkey";
            columns: ["cover_media_id"];
            isOneToOne: false;
            referencedRelation: "media";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "showcases_event_id_fkey";
            columns: ["event_id"];
            isOneToOne: false;
            referencedRelation: "events";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "showcases_event_type_id_fkey";
            columns: ["event_type_id"];
            isOneToOne: false;
            referencedRelation: "event_types";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "showcases_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          received_at: string;
          processed_at: string | null;
        };
        Insert: {
          id: string;
          type: string;
          received_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          type?: string;
          received_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      testimonials: {
        Row: {
          id: string;
          customer_name: string;
          customer_id: string | null;
          event_type_id: string | null;
          quote: string;
          rating: number;
          event_date: string | null;
          photo_url: string | null;
          source: string;
          is_published: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          customer_id?: string | null;
          event_type_id?: string | null;
          quote: string;
          rating?: number;
          event_date?: string | null;
          photo_url?: string | null;
          source?: string;
          is_published?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          customer_id?: string | null;
          event_type_id?: string | null;
          quote?: string;
          rating?: number;
          event_date?: string | null;
          photo_url?: string | null;
          source?: string;
          is_published?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "testimonials_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "testimonials_event_type_id_fkey";
            columns: ["event_type_id"];
            isOneToOne: false;
            referencedRelation: "event_types";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          role: Database["public"]["Enums"]["user_role"];
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "users_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      venues: {
        Row: {
          id: string;
          name: string;
          street: string | null;
          city: string;
          state: string;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          setting: string;
          parking_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          street?: string | null;
          city: string;
          state?: string;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          setting?: string;
          parking_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          street?: string | null;
          city?: string;
          state?: string;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          setting?: string;
          parking_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      check_rate_limit: { Args: { p_key: string; p_limit: number; p_window_seconds: number }; Returns: boolean };
      current_staff_role: { Args: Record<PropertyKey, never>; Returns: Database["public"]["Enums"]["user_role"] };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_staff: { Args: Record<PropertyKey, never>; Returns: boolean };
      next_document_number: { Args: { p_scope: string; p_at?: string }; Returns: string };
    };
    Enums: {
      ai_generation_status: "completed" | "failed" | "approved" | "discarded";
      automation_run_status: "pending" | "running" | "succeeded" | "failed" | "skipped" | "cancelled";
      availability_status: "unchecked" | "available" | "manual_review" | "unavailable";
      booking_status: "pending" | "confirmed" | "completed" | "cancelled";
      contract_status: "draft" | "sent" | "viewed" | "signed" | "void";
      delivery_status: "draft" | "queued" | "sent" | "delivered" | "failed" | "logged" | "discarded";
      lead_status: "new" | "contacted" | "qualified" | "quote_sent" | "awaiting_customer" | "contract_sent" | "contract_signed" | "deposit_pending" | "deposit_paid" | "confirmed" | "completed" | "lost" | "cancelled";
      media_kind: "image" | "video";
      message_direction: "outbound" | "inbound" | "internal";
      message_type: "email" | "sms" | "system" | "ai_draft" | "admin_note";
      payment_kind: "deposit" | "balance" | "other";
      payment_status: "unpaid" | "pending" | "paid" | "failed" | "refunded" | "partially_refunded";
      quote_status: "draft" | "sent" | "viewed" | "accepted" | "declined" | "expired" | "superseded";
      user_role: "owner" | "admin" | "staff";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];

export const Constants = {
  public: {
    Enums: {
      ai_generation_status: ["completed", "failed", "approved", "discarded"],
      automation_run_status: ["pending", "running", "succeeded", "failed", "skipped", "cancelled"],
      availability_status: ["unchecked", "available", "manual_review", "unavailable"],
      booking_status: ["pending", "confirmed", "completed", "cancelled"],
      contract_status: ["draft", "sent", "viewed", "signed", "void"],
      delivery_status: ["draft", "queued", "sent", "delivered", "failed", "logged", "discarded"],
      lead_status: ["new", "contacted", "qualified", "quote_sent", "awaiting_customer", "contract_sent", "contract_signed", "deposit_pending", "deposit_paid", "confirmed", "completed", "lost", "cancelled"],
      media_kind: ["image", "video"],
      message_direction: ["outbound", "inbound", "internal"],
      message_type: ["email", "sms", "system", "ai_draft", "admin_note"],
      payment_kind: ["deposit", "balance", "other"],
      payment_status: ["unpaid", "pending", "paid", "failed", "refunded", "partially_refunded"],
      quote_status: ["draft", "sent", "viewed", "accepted", "declined", "expired", "superseded"],
      user_role: ["owner", "admin", "staff"],
    },
  },
} as const;
